using RebankMarketingNetworkManagement.Application.Common.Interfaces.Repositories.Base;

namespace RebankMarketingNetworkManagement.Application.Common.Interfaces.Repositories.Distributor;

public interface IDistributorContactInformationRepository : IRepository<Domain.DistributorContactInformation>
{
}