using RebankMarketingNetworkManagement.Application.Common.Interfaces.Repositories.Base;

namespace RebankMarketingNetworkManagement.Application.Common.Interfaces.Repositories.Distributor;

public interface IDistributorPrivateDocumentInformationRepository : IRepository<Domain.DistributorPrivateDocumentInformation>
{
}